import type { Product, Review } from "@/types";

export const PRODUCTS: Product[] = [
  {
    id: "prod_hair",
    handle: "lumisca-pro-hair-growth-cap",
    name: "Lumisca Pro Red Light Hair Growth Cap",
    shortName: "Pro Hair Growth Cap",
    tagline: "Clinical red light therapy for thicker, fuller hair.",
    description:
      "Clinical-grade red light therapy cap for hair regrowth. Dual wavelength 650nm + 850nm. Hands-free. 25 minute sessions. Rechargeable. For men and women.",
    longDescription:
      "The Lumisca Pro delivers the exact wavelengths used in Harley Street hair clinics — 650nm visible red and 850nm near-infrared — directly to your scalp via 272 medical-grade LEDs. Clinically studied to stimulate dormant follicles, extend the anagen growth phase and thicken each individual hair shaft. Fully rechargeable, completely cordless, and designed to wear while you work, read or watch TV.",
    price: 64.99,
    compareAtPrice: 129.99,
    category: "hair",
    badge: "Bestseller",
    rating: 4.9,
    reviewCount: 1248,
    benefits: [
      "Clinically studied wavelengths (650nm + 850nm)",
      "Stimulates dormant hair follicles",
      "Hands-free, wear-while-you-work design",
      "25 minute auto-shutoff timer",
      "USB-C rechargeable — fully cordless",
      "Fits all head sizes with flex-band",
      "Visible results from week 8-12",
    ],
    benefitIcons: [
      { icon: "⚡", title: "272 Medical LEDs", description: "Clinic-grade coverage across entire scalp" },
      { icon: "🔬", title: "Dual Wavelength", description: "650nm surface + 850nm deep penetration" },
      { icon: "🙌", title: "Hands-Free", description: "Wear while you work, cook or watch TV" },
      { icon: "⏱", title: "25 Min Sessions", description: "Auto-shutoff so you can't overdo it" },
      { icon: "🔋", title: "USB-C Charging", description: "Up to 6 sessions on one charge" },
      { icon: "📏", title: "One-Size-Fits-All", description: "Flex-band adjusts for every head" },
    ],
    inTheBox: ["Lumisca Pro Hair Cap", "USB-C charging cable", "Premium carry pouch", "Illustrated user guide"],
    howToUse: [
      "Clean, dry scalp — no oils or serums before use.",
      "Pull the cap onto your head, ensuring all LEDs contact scalp.",
      "Press the power button once to begin a 25-minute session.",
      "Use 4-5 times per week, consistently, for at least 12 weeks.",
      "Results appear from week 8 — keep going, the best is at month 6+.",
    ],
    specs: [
      { label: "Wavelengths", value: "650nm red + 850nm near-infrared" },
      { label: "LED count", value: "272 medical-grade diodes" },
      { label: "Session length", value: "25 minutes (auto-shutoff)" },
      { label: "Battery", value: "Rechargeable lithium-ion, USB-C" },
      { label: "Battery life", value: "Up to 6 sessions per charge" },
      { label: "Fit", value: "One size — adjustable flex-band" },
      { label: "Weight", value: "345g" },
      { label: "Warranty", value: "2-year Lumisca warranty" },
    ],
    timeline: [
      { week: "Week 1", title: "Begin Your Routine", description: "Scalp feels healthier. No visible changes yet — this is normal." },
      { week: "Week 4", title: "Reduced Shedding", description: "Most customers report noticeably less hair in the shower and brush." },
      { week: "Week 8", title: "Baby Hairs Emerge", description: "Fine new growth appears at hairline and thinning patches." },
      { week: "Week 12+", title: "Visible Thickness", description: "Density, coverage and thickness have all measurably improved." },
    ],
    stats: [
      { value: "650nm", label: "Peak absorption for hair follicles" },
      { value: "31%", label: "Average increase in hair count (clinical studies)" },
      { value: "92%", label: "Of users see results by week 12" },
    ],
    images: [
      { src: "", alt: "Lumisca Pro Hair Growth Cap — front view", placeholder: "Pro Hair Cap — Front" },
      { src: "", alt: "Lumisca Pro Hair Growth Cap — interior LEDs", placeholder: "Pro Hair Cap — Interior" },
      { src: "", alt: "Lumisca Pro Hair Growth Cap — being worn", placeholder: "Pro Hair Cap — Lifestyle" },
      { src: "", alt: "Lumisca Pro Hair Growth Cap — controls close-up", placeholder: "Pro Hair Cap — Detail" },
    ],
    stock: 23,
    soldLast24h: 47,
    viewingNow: 12,
    featured: true,
  },
  {
    id: "prod_face",
    handle: "lumisca-glow-face-mask",
    name: "Lumisca Glow Red Light Face Mask",
    shortName: "Glow Face Mask",
    tagline: "Clinic-grade LED skincare, hands-free.",
    description:
      "Hands-free LED therapy mask combining red and near-infrared light to reduce fine lines, boost collagen and even skin tone. Flexible medical-grade silicone.",
    longDescription:
      "The Glow Mask flexes to the contours of your face thanks to medical-grade silicone, delivering 7 clinically selected light modes across red, near-infrared, amber and blue spectrums. Red stimulates collagen and elastin, near-infrared penetrates deeper to calm inflammation, amber evens tone and blue targets breakout bacteria. A single 20 minute session replaces a £80 London facial.",
    price: 54.99,
    compareAtPrice: 109.99,
    category: "face",
    badge: "Viral on TikTok",
    rating: 4.9,
    reviewCount: 892,
    benefits: [
      "7 clinical light modes (red, near-infrared, amber, blue and combos)",
      "Flexible medical-grade silicone — contours to every face",
      "Full face, neck and jawline coverage",
      "Completely hands-free — no wires, no stand",
      "20 minute auto-shutoff timer",
      "USB-C rechargeable",
      "Visible results from week 4",
    ],
    benefitIcons: [
      { icon: "✨", title: "7 Light Modes", description: "Target wrinkles, tone, acne and redness" },
      { icon: "🪷", title: "Medical Silicone", description: "Soft, flexible and gentle on every skin type" },
      { icon: "👁", title: "Full Coverage", description: "Face, neck and jawline in one 20-min session" },
      { icon: "🙌", title: "Hands-Free", description: "Wear while reading, meditating or skincare prep" },
      { icon: "⏱", title: "20 Min Auto-Timer", description: "Clinically optimal session length" },
      { icon: "🔋", title: "USB-C Charging", description: "Cordless freedom between sessions" },
    ],
    inTheBox: ["Lumisca Glow Face Mask", "USB-C charging cable", "Premium storage bag", "Protective eye shields", "Illustrated user guide"],
    howToUse: [
      "Cleanse your face — avoid serums or oils before use.",
      "Insert the included eye shields to protect your eyes.",
      "Slip the mask on, fasten the silicone strap.",
      "Select your light mode and begin your 20-minute session.",
      "Use 4-5 times per week. Apply serum immediately after for maximum absorption.",
    ],
    specs: [
      { label: "Light modes", value: "7 (red, near-infrared, amber, blue + combinations)" },
      { label: "LED count", value: "192 medical-grade diodes" },
      { label: "Session length", value: "20 minutes (auto-shutoff)" },
      { label: "Material", value: "Medical-grade silicone (hypoallergenic)" },
      { label: "Battery", value: "Rechargeable lithium-ion, USB-C" },
      { label: "Battery life", value: "Up to 8 sessions per charge" },
      { label: "Weight", value: "210g" },
      { label: "Warranty", value: "2-year Lumisca warranty" },
    ],
    timeline: [
      { week: "Week 1", title: "Skin Feels Plumper", description: "Most customers notice a fresh, calmer, more hydrated complexion." },
      { week: "Week 4", title: "Brighter, Even Tone", description: "Post-inflammatory marks begin to fade, skin looks visibly brighter." },
      { week: "Week 8", title: "Fine Lines Soften", description: "Collagen production has ramped up. Fine lines around eyes and mouth reduce." },
      { week: "Week 12+", title: "Transformed Skin", description: "Smoother texture, tighter pores and that lit-from-within glow." },
    ],
    stats: [
      { value: "630nm", label: "Peak wavelength for collagen stimulation" },
      { value: "35%", label: "Increase in collagen density (clinical studies)" },
      { value: "88%", label: "Of users report visible improvement by week 8" },
    ],
    images: [
      { src: "", alt: "Lumisca Glow Face Mask — on model", placeholder: "Glow Mask — Lifestyle" },
      { src: "", alt: "Lumisca Glow Face Mask — interior LEDs", placeholder: "Glow Mask — Interior" },
      { src: "", alt: "Lumisca Glow Face Mask — front view", placeholder: "Glow Mask — Front" },
      { src: "", alt: "Lumisca Glow Face Mask — packaging", placeholder: "Glow Mask — Packaging" },
    ],
    stock: 18,
    soldLast24h: 62,
    viewingNow: 24,
    featured: true,
  },
  {
    id: "prod_eye",
    handle: "lumisca-rest-eye-mask",
    name: "Lumisca Rest Heated Eye Mask",
    shortName: "Rest Heated Eye Mask",
    tagline: "Better sleep, calmer eyes, clearer mornings.",
    description:
      "Cordless rechargeable heated eye mask with 3 temperature settings and optional vibration massage. For better sleep, dry eye relief, migraine ease and screen fatigue recovery.",
    longDescription:
      "The Rest Mask warms to three precise temperatures (38°C, 42°C, 46°C), melting away tension and screen fatigue in 15 minutes. Optional gentle vibration massage stimulates the acupressure points around the eyes. Memory foam moulds to your face, and because it's completely cordless, you can use it anywhere — plane, sofa, bed.",
    price: 29.99,
    compareAtPrice: 59.99,
    category: "eye",
    badge: "Staff Favourite",
    rating: 4.8,
    reviewCount: 714,
    benefits: [
      "3 precise heat settings (38°C / 42°C / 46°C)",
      "Optional vibration massage at 2 intensities",
      "Cordless USB-C rechargeable",
      "Adjustable memory foam strap",
      "15 minute auto-shutoff",
      "Soft memory-foam lining",
      "Travel-friendly — carry pouch included",
    ],
    benefitIcons: [
      { icon: "🔥", title: "3 Heat Settings", description: "38°C, 42°C and 46°C clinical temperatures" },
      { icon: "💆", title: "Vibration Massage", description: "2 intensities for eye tension and migraines" },
      { icon: "🔋", title: "Cordless USB-C", description: "Up to 10 sessions per charge" },
      { icon: "☁️", title: "Memory Foam", description: "Plush lining that moulds to your face" },
      { icon: "⏱", title: "15 Min Auto-Off", description: "Drift off knowing it won't stay on" },
      { icon: "✈️", title: "Travel-Friendly", description: "Compact carry pouch for anywhere" },
    ],
    inTheBox: ["Lumisca Rest Eye Mask", "USB-C charging cable", "Premium travel pouch", "Illustrated user guide"],
    howToUse: [
      "Charge fully before first use (USB-C, ~90 minutes).",
      "Place the mask gently over your closed eyes.",
      "Press power once for 38°C, twice for 42°C, three times for 46°C.",
      "Long-press the massage button to toggle vibration.",
      "Use 10-15 minutes before bed, or after screen-heavy work.",
    ],
    specs: [
      { label: "Heat settings", value: "38°C / 42°C / 46°C" },
      { label: "Massage", value: "2 vibration intensities (optional)" },
      { label: "Session length", value: "15 minutes (auto-shutoff)" },
      { label: "Battery", value: "Rechargeable lithium-ion, USB-C" },
      { label: "Battery life", value: "Up to 10 sessions per charge" },
      { label: "Material", value: "Memory foam + skin-friendly fabric" },
      { label: "Weight", value: "165g" },
      { label: "Warranty", value: "1-year Lumisca warranty" },
    ],
    timeline: [
      { week: "Night 1", title: "Instant Calm", description: "Eye strain melts away. Most customers fall asleep wearing it." },
      { week: "Week 1", title: "Deeper Sleep", description: "Cumulative effect — your body starts associating the warmth with rest." },
      { week: "Week 4", title: "Dry Eye Relief", description: "Regular warm compress cycles unblock meibomian glands." },
      { week: "Ongoing", title: "Your Evening Ritual", description: "Part of your wind-down routine — better sleep, calmer mornings." },
    ],
    stats: [
      { value: "42°C", label: "Clinical temperature for meibomian gland dysfunction" },
      { value: "15 min", label: "Optimal warm compress duration per ophthalmology guidance" },
      { value: "94%", label: "Of users report better sleep within 2 weeks" },
    ],
    images: [
      { src: "", alt: "Lumisca Rest Eye Mask — on model", placeholder: "Rest Mask — Lifestyle" },
      { src: "", alt: "Lumisca Rest Eye Mask — interior lining", placeholder: "Rest Mask — Interior" },
      { src: "", alt: "Lumisca Rest Eye Mask — front view", placeholder: "Rest Mask — Front" },
      { src: "", alt: "Lumisca Rest Eye Mask — travel pouch", placeholder: "Rest Mask — Travel" },
    ],
    stock: 41,
    soldLast24h: 29,
    viewingNow: 9,
  },
  {
    id: "prod_bundle",
    handle: "lumisca-complete-bundle",
    name: "Lumisca Complete Bundle",
    shortName: "Complete Bundle",
    tagline: "Your complete at-home light therapy clinic.",
    description:
      "Your complete at-home light therapy clinic. All 3 Lumisca devices in one beautifully packaged box.",
    longDescription:
      "The Complete Bundle is how most of our best results start. Pro Hair Growth Cap, Glow Face Mask and Rest Heated Eye Mask — delivered together in a single branded gift box with a handwritten welcome card and quick-start guide. You save over £174 versus buying the three devices individually, and you'll have a daily light therapy routine for hair, skin and sleep from day one.",
    price: 124.99,
    compareAtPrice: 299.97,
    category: "bundle",
    badge: "Best Value",
    rating: 4.9,
    reviewCount: 486,
    benefits: [
      "All 3 Lumisca devices — hair, face and eyes",
      "Save £174.98 vs buying individually (58% saving)",
      "Branded gift-ready box",
      "Handwritten welcome card",
      "Quick-start routine guide",
      "Free UK priority delivery",
      "60-day money-back guarantee on the full bundle",
    ],
    benefitIcons: [
      { icon: "🎁", title: "Gift-Ready Packaging", description: "Premium branded gift box with welcome card" },
      { icon: "💸", title: "Save £174.98", description: "58% saving versus buying individually" },
      { icon: "📖", title: "Routine Guide", description: "Quick-start instructions for a 15-min daily routine" },
      { icon: "🚚", title: "Priority Delivery", description: "Free UK next-working-day delivery" },
      { icon: "🛡", title: "60-Day Guarantee", description: "Love it or full refund, no questions asked" },
      { icon: "🎯", title: "Hair + Skin + Sleep", description: "One purchase covers your full wellness routine" },
    ],
    inTheBox: [
      "Lumisca Pro Red Light Hair Growth Cap",
      "Lumisca Glow Red Light Face Mask",
      "Lumisca Rest Heated Eye Mask",
      "Branded gift box",
      "Handwritten welcome card",
      "Quick-start routine guide",
      "All USB-C cables and accessories",
    ],
    howToUse: [
      "Morning: Use the Glow Face Mask while your morning coffee brews (20 min).",
      "Afternoon or evening: Use the Pro Hair Cap while working, reading or watching TV (25 min).",
      "Before bed: Slip on the Rest Eye Mask 15 minutes before sleep.",
      "Consistency is everything — aim for 4-5 days per week across all three.",
      "Expect hair results from week 8-12, skin from week 4, sleep from night one.",
    ],
    specs: [
      { label: "Includes", value: "Pro Hair Cap + Glow Face Mask + Rest Eye Mask" },
      { label: "RRP", value: "£299.97" },
      { label: "Bundle price", value: "£124.99 (save £174.98)" },
      { label: "Packaging", value: "Branded gift box, welcome card, routine guide" },
      { label: "Warranty", value: "2-year warranty on all devices" },
      { label: "Delivery", value: "Free UK priority delivery" },
    ],
    timeline: [
      { week: "Week 1", title: "Settle Into The Routine", description: "Sleep improves immediately. Skin feels fresher day one." },
      { week: "Week 4", title: "Visible Skin Change", description: "Brighter, more even tone. Reduced shedding begins." },
      { week: "Week 8", title: "New Hair Growth", description: "Baby hairs emerge at hairline and thinning areas." },
      { week: "Week 12+", title: "Full Transformation", description: "Thicker hair, glowing skin, consistently better sleep." },
    ],
    stats: [
      { value: "3-in-1", label: "Complete hair, skin and sleep routine" },
      { value: "£174", label: "Total saving versus individual purchase" },
      { value: "97%", label: "Of bundle buyers would recommend to a friend" },
    ],
    images: [
      { src: "", alt: "Lumisca Complete Bundle — all three devices", placeholder: "Complete Bundle — Hero" },
      { src: "", alt: "Lumisca Complete Bundle — gift box open", placeholder: "Bundle — Gift Box" },
      { src: "", alt: "Lumisca Complete Bundle — lifestyle", placeholder: "Bundle — Lifestyle" },
      { src: "", alt: "Lumisca Complete Bundle — welcome card", placeholder: "Bundle — Welcome Card" },
    ],
    stock: 12,
    soldLast24h: 21,
    viewingNow: 17,
    featured: true,
  },
];

export function getProduct(handle: string): Product | undefined {
  return PRODUCTS.find((p) => p.handle === handle);
}

export function getProductsExcept(handle: string): Product[] {
  return PRODUCTS.filter((p) => p.handle !== handle);
}

export const REVIEWS: Review[] = [
  {
    id: "rev_1",
    name: "Sarah M.",
    location: "Manchester",
    rating: 5,
    title: "My hairdresser noticed before I even told her.",
    body: "I've been losing my hair since menopause and tried everything. 10 weeks with the Lumisca cap and I genuinely can't believe the difference. My hairdresser noticed before I even told her.",
    productHandle: "lumisca-pro-hair-growth-cap",
    verified: true,
    date: "2026-03-12",
  },
  {
    id: "rev_2",
    name: "David K.",
    location: "Leeds",
    rating: 5,
    title: "New growth at the temples.",
    body: "Started using this in January for my receding hairline. New growth coming through at the temples. My wife is now stealing it for her thinning crown.",
    productHandle: "lumisca-pro-hair-growth-cap",
    verified: true,
    date: "2026-03-28",
  },
  {
    id: "rev_3",
    name: "Claire B.",
    location: "Edinburgh",
    rating: 5,
    title: "Paid for itself in the first month.",
    body: "I was spending £80 a month on facials. This paid for itself in the first month. My skin looks genuinely brighter after 6 weeks.",
    productHandle: "lumisca-glow-face-mask",
    verified: true,
    date: "2026-02-18",
  },
  {
    id: "rev_4",
    name: "Priya S.",
    location: "London",
    rating: 5,
    title: "Dark marks have faded significantly.",
    body: "Bought for acne scarring. 8 weeks and the dark marks have faded significantly. My skin texture has completely changed.",
    productHandle: "lumisca-glow-face-mask",
    verified: true,
    date: "2026-03-04",
  },
  {
    id: "rev_5",
    name: "James T.",
    location: "Birmingham",
    rating: 5,
    title: "Best sleep I've had in years.",
    body: "Work in front of screens 10 hours a day. 15 minutes before bed and I sleep better than I have in years.",
    productHandle: "lumisca-rest-eye-mask",
    verified: true,
    date: "2026-03-22",
  },
  {
    id: "rev_6",
    name: "Emma R.",
    location: "Dublin",
    rating: 5,
    title: "The whole bundle changed my routine.",
    body: "Bought the full bundle. Use all three every day. Hair cap showing real results at week 8, skin is glowing, haven't had a bad sleep since.",
    productHandle: "lumisca-complete-bundle",
    verified: true,
    date: "2026-03-30",
  },
  {
    id: "rev_7",
    name: "Rachel D.",
    location: "Bristol",
    rating: 5,
    title: "Husband thought I'd had Botox.",
    body: "Using the Glow Mask five nights a week. Husband thought I'd had Botox at week 10. I'm 47 and my skin has not looked this good in a decade.",
    productHandle: "lumisca-glow-face-mask",
    verified: true,
    date: "2026-02-02",
  },
  {
    id: "rev_8",
    name: "Tom W.",
    location: "Glasgow",
    rating: 5,
    title: "Sceptical at first — now a convert.",
    body: "Honestly thought this would be gimmicky. 12 weeks in and I'm telling everyone who'll listen. My thinning crown is visibly denser.",
    productHandle: "lumisca-pro-hair-growth-cap",
    verified: true,
    date: "2026-01-22",
  },
  {
    id: "rev_9",
    name: "Nadia H.",
    location: "Cardiff",
    rating: 5,
    title: "Migraine relief within minutes.",
    body: "I get tension migraines from screens. The Rest Mask on 42°C for 15 minutes stops them in their tracks every time.",
    productHandle: "lumisca-rest-eye-mask",
    verified: true,
    date: "2026-03-09",
  },
  {
    id: "rev_10",
    name: "Olivia P.",
    location: "Brighton",
    rating: 5,
    title: "The bundle is the no-brainer option.",
    body: "Saving £175 on the bundle sold me. Now three months in and it's the best wellness spend I've ever made. My skin, my hair, my sleep all improved.",
    productHandle: "lumisca-complete-bundle",
    verified: true,
    date: "2026-03-18",
  },
  {
    id: "rev_11",
    name: "Harry G.",
    location: "Newcastle",
    rating: 4,
    title: "Works, but takes patience.",
    body: "Took me until week 10 to see clear results on my hairline. Worth it, but anyone expecting miracles in a month — that's not how this works. Stick with it.",
    productHandle: "lumisca-pro-hair-growth-cap",
    verified: true,
    date: "2026-02-26",
  },
  {
    id: "rev_12",
    name: "Ayesha K.",
    location: "Sheffield",
    rating: 5,
    title: "My skin looks its best at 51.",
    body: "I've used everything — retinol, peels, microneedling. This is the first at-home device that has genuinely made a visible, lasting difference. Pores smaller, texture smoother, tone brighter.",
    productHandle: "lumisca-glow-face-mask",
    verified: true,
    date: "2026-03-15",
  },
];

export function getReviewsForProduct(handle: string): Review[] {
  return REVIEWS.filter((r) => r.productHandle === handle);
}
